[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=4
upload_protocol = esptool
upload_port = /dev/cu.usbserial-110

lib_deps =
    fastled/FastLED
    adafruit/Adafruit GFX Library
    marcmerlin/FastLED NeoMatrix
    knolleary/PubSubClient


; monitor_port = /dev/cu.usbserial-110s
; upload_protocol = espota
; upload_port = 192.168.0.45